Rule Component/src/objects/Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>This field will hold the different comparison operators.</description>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>does not contain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>starts with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>isChanged</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rule_No__c</fullName>
        <label>Rule No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ValueType__c</fullName>
        <label>ValueType</label>
        <picklist>
            <picklistValues>
                <fullName>Value</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>API</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>This can be either a field API name or any value</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Criteria</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Criteria Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rule Component/src/objects/Rule__c.object
<CustomObject>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>This field will signify the object name.</description>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Condition__c</fullName>
        <description>&quot;This field will contain the logical operators for the rule. It supports only 1 level 
e.g. - ((1 OR 2) AND (3 OR 5) OR (6 AND 7))&quot;</description>
        <label>Rule Condition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topic_Name__c</fullName>
        <description>This field will signify the topic name</description>
        <label>Topic Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TriggerEvents__c</fullName>
        <label>TriggerEvents</label>
        <picklist>
            <picklistValues>
                <fullName>before insert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>before update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>before delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>after insert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>after update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>after delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>after undelete</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Rule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rule Component/src/objects/Rule_Criterias__c.object
<CustomObject>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <referenceTo>Criteria__c</referenceTo>
        <relationshipLabel>Rule Criterias</relationshipLabel>
        <relationshipName>Rule_Criterias</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>Rule__c</referenceTo>
        <relationshipLabel>Rule Criterias</relationshipLabel>
        <relationshipName>Rule_Criterias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Criterias</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Rule Criterias Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Rule Component/src/objects/Topic__c.object
<CustomObject>
    <description>This object will store all topic related information for an event. For all connected system, topic Ids will have to be mapped. 
Either all systems maintain the same Topic Id or there is a mapping object to map Topics across the system and is always in sync.</description>
    <label>ENS_Topic</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Topic Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ENS_Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Rule Component/src/classes/RuleEngineController.cls
/*
 *	Description : This class with validate all the topic associated rules & rule criterias.
 */
public with sharing class RuleEngineController {
	
	public static Map<String,Topic__c> topicMap = new Map<String,Topic__c>();
	private static final String EQUALS = 'equals';
	// This method will validate all the associated criterias of sObject
	public static void checkForCriterias(Map<Id,sObject> pSobjectMap,String pObjectName,String pTriggerEvent){
		
		// Map of topic name & list of associated criterias
		Map<String,List<Criteria__c>> ruleCriteriaMap = new Map<String,List<Criteria__c>>();
		Set<String> topicSet = new Set<String>();
		System.debug('pSobjectMap===='+pSobjectMap);
		for(Rule_Criterias__c ruleCriteriasItr : [SELECT Id,
														 Rule__r.id,
														 Rule__r.Rule_Condition__c,
														 Rule__r.Topic_Name__c,
														 Rule__r.TriggerEvents__c,
														 Rule__r.Object_Name__c,
														 Criteria__r.isActive__c,	
														 Criteria__r.Field_Name__c,
														 Criteria__r.Operator__c,
														 Criteria__r.Value__c,
														 Criteria__r.Rule_No__c,
														 Criteria__r.ValueType__c
														 FROM Rule_Criterias__c 
														 WHERE Criteria__r.isActive__c=true AND
														  	   Rule__r.Object_Name__c =:pObjectName AND
														  	   Rule__r.TriggerEvents__c INCLUDES (:pTriggerEvent)]
														  	   ){
				System.debug('ruleCriteriasItr===='+ruleCriteriasItr);									  
			if(ruleCriteriaMap.containsKey(ruleCriteriasItr.Rule__r.Topic_Name__c) && ruleCriteriaMap.get(ruleCriteriasItr.Rule__r.Topic_Name__c)!=null && String.isNotBlank(ruleCriteriasItr.Rule__r.Topic_Name__c)){
				ruleCriteriaMap.get(ruleCriteriasItr.Rule__r.Topic_Name__c).add(new Criteria__c(Field_Name__c=ruleCriteriasItr.Criteria__r.Field_Name__c,
																			   Operator__c =ruleCriteriasItr.Criteria__r.Operator__c,
																			   Value__c=ruleCriteriasItr.Criteria__r.Value__c,
																			   Rule_No__c=ruleCriteriasItr.Criteria__r.Rule_No__c,
																			   ValueType__c=ruleCriteriasItr.Criteria__r.ValueType__c));
				topicSet.add(ruleCriteriasItr.Rule__r.Topic_Name__c);
			}
			else if(String.isNotBlank(ruleCriteriasItr.Rule__r.Topic_Name__c)){
				ruleCriteriaMap.put(ruleCriteriasItr.Rule__r.Topic_Name__c,new List<Criteria__c>{(new Criteria__c(Field_Name__c=ruleCriteriasItr.Criteria__r.Field_Name__c,
																			   Operator__c =ruleCriteriasItr.Criteria__r.Operator__c,
																			   Value__c=ruleCriteriasItr.Criteria__r.Value__c,
																			   Rule_No__c=ruleCriteriasItr.Criteria__r.Rule_No__c,
																			   ValueType__c=ruleCriteriasItr.Criteria__r.ValueType__c))});
				topicSet.add(ruleCriteriasItr.Rule__r.Topic_Name__c);
			}
		}// end - for loop
		
		if(!ruleCriteriaMap.isEmpty()){
			RuleEngineController.decodeRule(ruleCriteriaMap,pSobjectMap,pObjectName);
		}
	}
	
	// This method will decode all the rule & check for associated criterias
	public static void decodeRule(Map<String,List<Criteria__c>> pRuleCriteriaMap,Map<Id,sObject> pSobjectMap,String pObjectName){
		
		Schema.SObjectType res = Schema.getGlobalDescribe().get(pObjectName);
		System.debug('res===='+res);	
		if(res != null){
			Schema.Describesobjectresult dsr = Schema.getGlobalDescribe().get(pObjectName).getDescribe();
	        Map<String, Schema.SObjectField> sObjMap = dsr.fields.getMap();
	        sobject object_instance = res.newSObject();
	        
			for(sObject objItr : pSobjectMap.values()){
				object_instance = objItr;
				System.debug('object_instance===='+object_instance);	
				for(String topicNameItr : pRuleCriteriaMap.keySet()){
					
					if(pRuleCriteriaMap.get(topicNameItr) != null && !pRuleCriteriaMap.get(topicNameItr).isEmpty()){
						List<Criteria__c> criteriaLst = pRuleCriteriaMap.get(topicNameItr);
						
						for(Criteria__c criteriaItr : criteriaLst){
							if(criteriaItr.Operator__c == EQUALS && object_instance.get(criteriaItr.Field_Name__c) == Boolean.valueOf(criteriaItr.Value__c)){
								System.debug('Success!');
								
							}
						}
					}
				}
			}
		}
	}
	
	// This method will check for datatype & return true if matches else false.
	public static void checkforDatatype(String pDatatype,String pLeftParam,String pRighParam){
		
	}
}